version: 2
updates:
  - package-ecosystem: devcontainers
    assignees:
      - MicahWW
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: github-actions
    assignees:
      - MicahWW
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: npm
    assignees:
      - MicahWW
    directory: /
    schedule:
      interval: monthly
    ignore:
      - dependency-name: next
        update-types: [version-update:semver-major]
      - dependency-name: eslint-config-next
        update-types: [version-update:semver-major]
      - dependency-name: '@types/node'
        update-types: [version-update:semver-major]
      - dependency-name: eslint
        update-types: [version-update:semver-major]
      - dependency-name: typescript
        update-types: [version-update:semver-major]
    groups:
      next:
        patterns:
          - next
          - eslint-config-next
      react:
        patterns:
          - react
          - react-dom
          - '@types/react'
          - '@types/react-dom'
      tailwind:
        patterns:
          - tailwindcss
          - '@tailwindcss/postcss'
