version: 2
updates:
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: monthly
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: monthly
    groups:
      next:
        applies-to: version-updates
        patterns:
          - "next"
          - "eslint-config-next"
      react:
        applies-to: version-updates
        patterns:
          - "@types/react*"
        update-types:
          - "patch"
          - "minor"
        