name: Generate and push new tag

on:
  workflow_dispatch:
permissions:
  contents: write # required for pushing tags & publishing releases

jobs:
  CalVer-Creation:
    runs-on: ubuntu-latest

    steps:
      - name: Publish release and tag
        id: publish_release_and_tag
        uses: MicahWW/CalVer-Creation@v1
        with:
          set_build_metadata: 'false'
          timezone: 'America/Chicago'
          push_tag: 'true'
          publish_release: 'true'
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: ./.github/workflows/Azure-Build-and-Push.yml
        with:
          version_tag: ${{ steps.publish_release_and_tag.outputs.new_version }}